[package]
name = "krungkualalumpur/input-manager"
version = "0.1.4"
description = "A package to handle cross-platform Roblox input"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Maid = "nightcycle/maid@1.1.1"
