name: Continuous Integration
on:  
  push:
  pull_request:

jobs:
  format_checking:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Aftman Setup
        uses: ok-nick/setup-aftman@v0.4.2
      - name: run stylua
        run: |
          stylua src --check
  

